### ISSUE TITLE
invalid start byte \ some kind of scrambled html

### ISSUE THREAD

**Issue by infominer33** [Ruined1/HTMLArticleElementStripper#2] opened 2019-05-09 05:25 UTC
```
Traceback (most recent call last):
  File "articlestrip.py", line 23, in <module>
    line = f.readline()
  File "/home/infominer/.pyenv/versions/3.6.8/lib/python3.6/codecs.py", line 321, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte
```

[index.zip](https://github.com/Ruined1/HTMLArticleElementStripper/files/3160468/index.zip)

idk what that file is, but it borks the program, so I had to manually try each subfolder till I found the problem.

**Comment by DeeJayhX** [comment] 2019-05-09 05:54
That HTML file doesn't contain any usable information. Open it up and have a look. I'll see if I can implement an exception catch to handle scenarios like this one.

**Comment by DeeJayhX** [comment] 2019-05-09 06:16
Fixed in [latest commit](https://github.com/Ruined1/HTMLArticleElementStripper/commit/af921d0daa6759837abd0c0fdeeda548d4af3feb). Also cranked up details in console printing, so try to run the program again from your main directory and let me know how it goes, if everything is savvy, I'll close the issue.

**Comment by DeeJayhX** [comment] 2019-05-11 06:29
Tested this a couple times myself. Appears to be working as intended.

**Closed as completed by DeeJayhX** 2019-05-11 06:29 UTC
Labels: enhancement

**Comment by infominer33** [comment] 2019-05-11 06:31
yes looks really nice! I just ran it, and am remembering what the heck I was even doing, have a few download directories scattered around, hehe.

have a few more places to run it, but all looks good! :D

**Comment by GIR-pub** [comment] 2019-05-11 06:44
![image](https://user-images.githubusercontent.com/50385928/57566120-d063c980-7396-11e9-8f33-45d38cff0816.png)


beautiful.
